account/urls.py
from django.urls import path, include
from .views import index, django_signup, django_login
from django.conf.urls import url

app_name = 'account'

urlpatterns = [
    path('', index, name='index'),
    path('signup/', django_signup, name='signup'),
    path('login/', django_login, name='login'),
]

articles/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

app_name = 'articles'

urlpatterns = [
    path('', articleParent, name='articlesParent'),
    path('sports/', sportsParent, name='sportsParent'),
    path('tech/', techParent, name='techParent'),
    path('lifestyle/', lifestyleParent, name='lifestyleParent'),
    path('food/', foodParent, name='foodParent'),
    path('celeb/', celebParent, name='celebParent'),
    # path('sports/', sportsParent),

]

cretivox/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls'), name='landing'),
    path('shows/', include('shows.urls'), name='shows'),
    path('account/', include('account.urls'), name='account'),
    path('articles/', include('articles.urls'), name='articles'),

]

landing/urls.py
from django.contrib import admin
from django.urls import path

from .views import articleParent, landing

app_name = 'landing'

urlpatterns = [
    path('', landing, name='landing'),
    path('articles/', articleParent)
]

shows/urls.py
from django.contrib import admin
from django.urls import path

from .views import shows, showsDetail

app_name = 'shows'

urlpatterns = [
    path('', shows, name='shows'),
    path('show-detail/', showsDetail)
]

account/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.

landing/models.py
from django.db import models

# Create your models here.

shows/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)

class UserForm(forms.Form):
    username = forms.CharField(
        max_length=20,
        widget=forms.TextInput(attrs={
            'class':'inputText',
            'placeholder': 'Username'
            })
        )
    password = forms.CharField(
        max_length=20, 
        widget=forms.PasswordInput(attrs={
            'class':'inputText',
            'placeholder': 'Password'
            })
        )

    class Meta:
        model = User
        fields = ['username','password']


class UserCreateForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=150, required=False)
    email = forms.EmailField(max_length=100, required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', ]

account/views.py
from django.shortcuts import redirect, render, reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .forms import UserForm, UserCreateForm
from django.contrib import messages
from django.shortcuts import redirect, render, reverse
from django.http import HttpResponse

# Create your views here.


def index(request):
    if request.method == "GET":
        return render(request, "djaccindex.html")


# Similar to Story 10

# function 1: Sign up

def django_signup(request):
    f = UserCreateForm(request.POST)
    context = {
        'signupform': f
    }
    if request.method == "GET":
        return render(request, "djaccsignup.html", context)
    if request.method == 'POST':
        if f.is_valid():
            f.save()
            username = request.POST['username']
            password1 = request.POST['password1']
            context = {
                'username': username,
                'password': password1
            }
            return render(request, "djacclogin.html", context) 
    else:
        f = UserCreateForm()
 
    return render(request, 'djaccsignup.html', context)

# Function 2: Login
    # Initialize a user's Cart
    # Redirect to landing

def django_login(request):            
    context = {
        'loginform': UserForm()
    }
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if(user is not None):
            request.session['username'] = username
            login(request, user)
            request.method = "GET"
            return redirect(reverse('landing:landing'))
        else:
            return render(request, "djacclogin.html", context)
    return render(request, "djacclogin.html", context)

articles/views.py
from django.http import request
from django.shortcuts import render

# Create your views here.
def articleParent(request):
    return render(request, 'articleParent.html')

def sportsParent(request):
    context = {
        'forYouTitle' : 'Popular in Sports',
        'topNewsTitle' : 'Latest in Sports'
    }
    return render(request, 'categoryParent.html', context)

def techParent(request):
    context = {
        'forYouTitle' : 'Popular in Tech',
        'topNewsTitle' : 'Latest in Tech'
    }
    return render(request, 'categoryParent.html', context)

def lifestyleParent(request):
    context = {
        'forYouTitle' : 'Popular in Lifestyle',
        'topNewsTitle' : 'Latest in Lifestyle'
    }
    return render(request, 'categoryParent.html', context)

def celebParent(request):
    context = {
        'forYouTitle' : 'Popular in Celeb',
        'topNewsTitle' : 'Latest in Celeb'
    }
    return render(request, 'categoryParent.html', context)

def foodParent(request):
    context = {
        'forYouTitle' : 'Popular in Food',
        'topNewsTitle' : 'Latest in Food'
    }
    return render(request, 'categoryParent.html', context)

landing/views.py
from django.shortcuts import render

# Create your views here.
def landing(request):
    context = {
        'titleCardSmall' : 'Top News',
        'titleCardVideo' : 'Shows'
    }
    return render(request, 'landingParent.html', context)

def articleParent(request):
    return render(request, 'articleParent.html')

shows/views.py
from django.http import request
from django.shortcuts import render

# Create your views here.

def shows(request):
    context = {
        'titleCardSmall' : 'Latest Episode',
        'titleCardVideo' : 'All Episodes'
    }
    return render(request, 'showParent.html', context)

def showsDetail(request):
    return render(request, 'showDetail.html')

templates/articleComment.html
<h2>Comments</h2>
<br>
<textarea name="" id="" cols="30" rows="10"></textarea>
<br><br>
<button class="cta-full bg-white">Submit</button>
<br><br>

    <!-- Cards -->
<div class="container-pad16 wrapper-375 card-grid-verticalauto border-black10">
    <div>
        {% lorem 2 p %}
        <br>
    </div>
    <p>Afriza</p>
    <p>1 hours ago</p>
    <button class="cta-full bg-white">Reply</button>

</div>
<br>
<div class="container-pad16 wrapper-375 card-grid-verticalauto border-black10">
    <div>
        <h3>Apaan dah</h3>
    </div>
    <p>Afriza</p>
    <p>1 hours ago</p>
    <button class="cta-full bg-white">Reply</button>
</div>
<br>
<div class="container-pad16 wrapper-375 card-grid-verticalauto border-black10">
    <div>
        <h3>Apaan dah</h3>
        <br>
        <p>Afriza</p>
    </div>
    <button class="cta-full bg-white">Reply</button>
</div>
<br>

templates/articleParent.html
{% extends 'base.html' %}

<!-- Override base.html navbar -->
{% block navbar %}
    {% include 'navbarBack.html' %}
{% endblock navbar %}


{% block content %}
<head>
<style>

    q{
        font-size: 2em;
        font-style: italic;
        opacity: 0.5;
    }

    .quote {
        width: calc(100%-2em);
        text-align: center;
        border-left: 1px solid rgba(0,0,0,0.5);
        margin: 1em;
    }

    .articleSheet {
        width: calc(100% - 0);
        overflow: hidden;
        border-radius: 10px;
        margin-top: 50vh;
        
    }

    .heroImg{
        overflow: hidden;
        position: fixed;
        z-index: -1000;
        top: 2.5em;
        width: 100vw;
        height: 50vh;
        object-fit: cover;
        display: flex;
        justify-content: center;
        align-items: center;

    }

    .heroImg > img {
        object-fit: none;
        object-position: 50% 50%;
    }

    .btnContainer {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(109px, 1fr));    
        gap: .5em;
    }

    .articleImg {
        width: calc(100%-2em);
        height: auto;
        padding: 1em;
    }

    .articleParagraphs {
        font-size: 1.1em;
    }

    

</style>
</head>

<body>
    <section>
        <div class="heroImg">
            <img src="https://www.astra-agro.co.id/wp-content/uploads/2018/04/Wow-Inilah-4-Kebijakan-Pemerintah-Jokowi-yang-Jadi-Sorotan-Dunia-2.jpg" alt="" >
        </div>
    </section>
    <section class="articleSheet bg-white border-black10">
        <div class="container-pad16 wrapper-375">
            <p>Politics</p>
            <h1>Ini Arahan Lengkap Jokowi Demi Mencegah Meluasnya Covid-19 di Indonesia.</h1>
            <br><br>

            <!-- Author & Status -->
            <p>NEWS UPDATE</p>
            <p>By Writer's Name</p>
            <p>1 hour ago • 5 min read</p>
            <br><br>

            <!-- Buttons -->
            <div class="btnContainer">
                <button class="cta-3 bg-white">Like</button>
                <button class="cta-3 bg-white">Dislike</button>
                <button class="cta-3 bg-white">Save</button>
                <button class="cta-full bg-black">Share</button>
            </div>
            <br><br>
            
            <!-- Article Images -->
            <a href="https://www.astra-agro.co.id/wp-content/uploads/2018/04/Wow-Inilah-4-Kebijakan-Pemerintah-Jokowi-yang-Jadi-Sorotan-Dunia-2.jpg">
                <div class="articleImg">
                  <img src="https://www.astra-agro.co.id/wp-content/uploads/2018/04/Wow-Inilah-4-Kebijakan-Pemerintah-Jokowi-yang-Jadi-Sorotan-Dunia-2.jpg" alt="" width="100%">
                </div>
            </a>

            {% include 'landingNewsUpdate.html' %}

            <div class="quote">
                <q>Helloooo</q>
            </div>
        <div class="articleParagraphs">
            {% lorem 3 p %}
        </div>            <!-- Paragraphs -->

            <br><br>

            <!-- Tags -->
            {% include 'articleTags.html' %}
            <br><br>

            <!-- Comment Section -->
            {% include 'articleComment.html' %}
            </div>
    </section>

</body>

{% endblock %}

templates/articleTags.html
<head>
    <style>
        .containerTags{
            display: inline-block;
        }
    </style>
</head>

<h2>Tags</h2>
<br>
<div class="containerTags">
    <div class="tags border-black10">
        <a href="">News Update</a>
    </div>
    <div class="tags border-black10">
        <a href="">Sport</a>
    </div>
    <div class="tags border-black10">
        <a href="">Sport</a>
    </div>
    <div class="tags border-black10">
        <a href="">Sport</a>
    </div>
    <div class="tags border-black10">
        <a href="">Sport</a>
    </div>
    <div class="tags border-black10">
        <a href="">Sport</a>
    </div>
    <div class="tags border-black10">
        <a href="">Sport</a>
    </div>
    <div class="tags border-black10">
        <a href="">Sport</a>
    </div>
    <div class="tags border-black10">
        <a href="">Sport</a>
    </div>
    <div class="tags border-black10">
        <a href="">Sport</a>
    </div>
    <div class="tags border-black10">
        <a href="">Sport</a>
    </div>

</div>

templates/auth.html
{% extends 'base.html' %}

{% block navbar %}

{% endblock navbar %}

{% block content %}

<section class="container-pad16 wrapper-375">
    <h1>Login</h1>
    <form class="flexrow-llcl" action="{% url 'landing:landing' %}" method="post">
        {% csrf_token %} {% if form != None %} {{loginform}} {% else %}
        <br>
        <label for="username">Username: </label>
        <input id="id_username" type="text" name="username" placeholder="Unique username" value="{{ username }}" required>
        
        <label for="password">Password: </label>
        <input id="id_password" type="password" name="password" placeholder="Classified password" value="{{ password }}" required> 
        {% endif %}
       
        <input type="submit" class="cta-full bg-white" value="Login">

    </form>

</section>

{% endblock content %}

{% block footer %}

{% endblock footer %}

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Cretivox</title>

    <!-- Google Font  -->
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet">

    <style>
        .content{
            margin-top: 4em;

        }
    </style>
</head>
<body>
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock navbar%}
    
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

    {% block footer %}
    {% include 'footer.html' %}
    
{% endblock footer %}


</body>
</html>

templates/categoryParent.html
{% extends 'base.html' %}



{% block content %}
{% include 'landingNewsUpdate.html' %}
<br>
{% include 'landingTopNews.html' %}
<br>
{% include 'landingForYou.html' %}
{% endblock %}

templates/djaccindex.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>Django Account</title>
</head>

<body>
    <section class="container-100vh flexrow-ccc">
        <div class="flexrow-ccc">
            <div class="title">
                <h1>Are you new here?</h1>
            </div>
            <br> {% if user.is_authenticated %}
            <h2 class="welcome">Welcome back, {{ user.username }} !</h2>
            <p>You've succesfully login via Django</p>
            <a class="cta-white btn" href="{% url 'landing:landing'%}">Redirect to Dashboard!</a>
            <a class="logoutbtn btn" href="{% url 'logout'%}">logout</a> {% else %}

            <a class="cta-white btn" href="{% url 'account:signup' %}">Yes I am</a>
            <a class="cta-white btn" href="{% url 'account:login' %}">No, I have an account</a>{% endif %}
        </div>
    </section>

</body>

</html>

templates/djacclogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>Django Account Login</title>
</head>

<body>

    <section class="container-100vh flexrow-ccc">
        <div class="flexrow-ccc">
            <div class="title">
                <h1>May I ask who you are?</h1>
            </div>
            <br> {% if user.is_authenticated %}
            <h2 class="welcome">Welcome back, {{ user.username }} !</h2>
            <p>You've succesfully login via Django</p>
            <a class="cta-white btn" href="{% url 'landing:landing'%}">Redirect to Dashboard!</a>
            <a class="logoutbtn btn" href="{% url 'logout'%}">logout</a> {% else %}

            <form class="flexrow-llcl" action="{% url 'account:login' %}" method="post">
                {% csrf_token %} {% if form != None %} {{loginform}} {% else %}
                <br>
                <label for="username">Username: </label>
                <input id="id_username" type="text" name="username" placeholder="Unique username" value="{{ username }}" required>
                <label for="password">Password: </label>
                <input id="id_password" type="password" name="password" placeholder="Classified password" value="{{ password }}" required> {% endif %}
                <input type="submit" class="loginbtn cta-white btn" value="Login!">

            </form>
            <a href="/account/signup">
                <p>Sign Up!</p>{% endif %}
        </div>
    </section>
</body>

</html>

templates/footer.html
<section class="bg-black">
    <div class="container-pad16">
        <h1>CRETIVOX</h1>
<br><br>
        <!-- Subscribe Card -->
        <div class="card-grid-vertical3 container-pad16 border-white">
            <p>Sign-up for the Complex Newsletter for breaking news, events, and unique stories</p>
            <input class="bg-black" type="email" name="" id="" placeholder="duar@cretivox.com">
            <input type="submit" value="Subscribe">        
        </div>
    </div>
</section>

templates/forYouCard.html
<div class="hover container-pad16 card-grid-vertical2 border-black10 bg-white">
    <div class="card-grid-horizontal2-l">
        <h1>Title</h1>
        <div class=" bg-red">Img</div>
    </div>
    <div class="card-grid-horizontal2-l">
        <p>Kompas  •  1 hour ago</p>
        <p style="text-align: right;">•••</p>
    </div>
</div>

templates/landingForYou.html
<!-- The Container -->
<div class="container-pad16 wrapper-375">
    <h1>{{forYouTitle}}</h1>
</div>
<div class="container-pad16 wrapper-375">
    <!-- For You Card -->
    {% include 'forYouCard.html' %}
</div>

{% for card in landingForYou.items %}

{% endfor %}

templates/landingNewsUpdate.html
<head>
    <style>
        .container{
            display: grid;
            justify-content: start;
            align-content: flex-end;
            width: auto;
            max-width: 332px;
            height: 208px;
            padding: 1em;
            margin: 0 auto;
            background-image: 
                linear-gradient(rgba(0, 0, 0, 0.6),
                rgba(0, 0, 0, 0.6)), 
                url('https://www.astra-agro.co.id/wp-content/uploads/2018/04/Wow-Inilah-4-Kebijakan-Pemerintah-Jokowi-yang-Jadi-Sorotan-Dunia-2.jpg');
            background-size: cover;
            color: white;

        }
    </style>
</head>
<!-- Top News Card -->
<div class="container-pad16 horizontal-scroll wrapper-375">
    <div class="wrapper-inline">
        <div class="hover container border-black10">
            <div>
                <h1>Ini Arahan Lengkap
                    Jokowi Demi Mencegah..
                </h1>
            </div>
            <div>            
                <p>Kompas  •  1 hour ago</p>
            </div>
        </div>
    </div>
    <div class="wrapper-inline">
        <div class="hover container border-black10">
            <div>
                <h1>Ini Arahan Lengkap
                    Jokowi Demi Mencegah..
                </h1>
            </div>
            <div>            
                <p>Kompas  •  1 hour ago</p>
            </div>
        </div>
    </div>
    <div class="wrapper-inline">
        <div class="hover container border-black10">
            <div>
                <h1>Ini Arahan Lengkap
                    Jokowi Demi Mencegah..
                </h1>
            </div>
            <div>            
                <p>Kompas  •  1 hour ago</p>
            </div>
        </div>
    </div>

</div>

{% for card in landingForYou.items %}

{% endfor %}

templates/landingSlideNav.html
<div class="container-pad16 wrapper-375 horizontal-scroll">
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>
    <a href="" class="slideNav">News Update</a>

</div>

templates/navbarrr.html
<head>

    <style>
        #containerNavUp {
            display: grid;
            grid-template-columns: 1fr auto 1fr;
            width: calc(100% - 2em);
            position: fixed;
            top: 0px;
            padding: .75em 1em .75em 1em;
            align-items: center;

        }

        #burgerNav {
            text-align: right;
        }

        .sidenav {
        height: 100%;
        width: 0;
        position: fixed;
        z-index: 1;
        top: 0;
        right: 0;
        background-color: #111;
        overflow-x: hidden;
        transition: 0.5s;
        padding-top: 60px;
        }

        .sidenav a {
        padding: 8px 8px 8px 32px;
        text-decoration: none;
        font-size: 25px;
        color: #818181;
        display: block;
        transition: 0.3s;
        }

        .sidenav a:hover {
        color: #f1f1f1;
        }

        .sidenav .closebtn {
        position: absolute;
        top: 0;
        right: 25px;
        font-size: 36px;
        margin-left: 50px;
        }

        @media screen and (max-height: 450px) {
        .sidenav {padding-top: 15px;}
        .sidenav a {font-size: 18px;}
        }
    </style>

</head>

<div id="containerNavUp" class="bg-white">
    <div id="mainSearch">
        <a href="">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M15.5 14H14.71L14.43 13.73C15.41 12.59 16 11.11 16 9.5C16 5.91 13.09 3 9.5 3C5.91 3 3 5.91 3 9.5C3 13.09 5.91 16 9.5 16C11.11 16 12.59 15.41 13.73 14.43L14 14.71V15.5L19 20.49L20.49 19L15.5 14ZM9.5 14C7.01 14 5 11.99 5 9.5C5 7.01 7.01 5 9.5 5C11.99 5 14 7.01 14 9.5C14 11.99 11.99 14 9.5 14Z" fill="black"/>
            </svg>                
        </a>
    </div>
    <div>
        <h1>CRETIVOX</h1>
    </div>
    <div id="burgerNav" onclick="openNav()">
        <a href="">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M3 18H21V16H3V18ZM3 13H21V11H3V13ZM3 6V8H21V6H3Z" fill="black"/>
            </svg>                
        </a>
    </div>
</div>

<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="#">Profile</a>
    <a href="#">Library</a>
    <a href="#">Home</a>
    <a href="#">Shows</a>
    <a href="#">Virals</a>
    <a href="#">Categories</a>
  </div>
  
  <script>
    function openNav() {
      document.getElementById("mySidenav").style.width = "250px";
    }
    
    function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
    }
</script>
    